version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/step1_bootstrap
      timeout: 120
      runas: root
    - location: scripts/step2_install_dependencies
      timeout: 1800
      runas: root
    - location: scripts/step3_clone_repositories
      timeout: 120
      runas: root
    - location: scripts/step4_build_repositories
      timeout: 300
      runas: root
    - location: scripts/step5_develop_repositories
      timeout: 120
      runas: root
    - location: scripts/step6_run_tests
      timeout: 600
      runas: root
    - location: scripts/step7_start_tmux_web_server
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/step8_kill_tmux_web_server
      timeout: 60
      runas: root

