#!/bin/sh
echo 'CHECKING'
tmux has-session -t ibeis-ia-codedeploy-web-server 2> /dev/null
if [ "$?" -eq 1 ] ; then
    echo '    SKIPPED'
else
    echo '    KILLED'
    tmux kill-session -t ibeis-ia-codedeploy-web-server
fi

