#!/bin/bash
cd /opt/ibeis/ibeis
./_scripts/__install_dependencies.sh
sudo apt-get install libopencv-dev python-opencv
sudo pip -y uninstall Theano
sudo pip -y uninstall Lasagne
cd ../
git clone https://github.com/Theano/Theano.git
cd Theano
sudo python setup.py develop
cd ../
git clone https://github.com/lisa-lab/pylearn2.git
cd pylearn2
sudo python setup.py develop
cd ../
git https://github.com/Lasagne/Lasagne.git
cd Lasagne
sudo python setup.py develop
cd ../
cd ibeis
