#!/bin/bash -ex
cd /opt/ibeis/ibeis
./super_setup.py --checkout next
./super_setup.py --pull
./super_setup.py --build
# Ensure flukematch built
cd ../
cd ibeis-flukematch-module
./unix_build.sh
cd ../
cd ibeis
# CodeDeploy is half-baked
sudo rm -rf /opt/codedeploy-agent/state/.pid
sudo service codedeploy-agent restart

