#!/bin/bash -ex
cd /opt/
if [ ! -d ibeis ]; then
    sudo mkdir ibeis
    sudo chown ubuntu ibeis
fi
cd ibeis
sudo apt-get -y install git
sudo apt-get -y install tmux
sudo apt-get -y install htop
if [ ! -d ibeis ]; then
    git clone https://github.com/Erotemic/ibeis.git
fi
cd ibeis
git checkout next
git pull
./super_setup.py --bootstrap

