#!/bin/bash -ex
cd /
sudo mkdir data
cd data
sudo mkdir ibeis
sudo chown ubuntu ibeis
cd /opt/ibeis/ibeis
./super_setup.py --pull
sudo rm -rf ~/.theano
if [ ! -f /dev/raw1394 ]; then
    sudo ln /dev/null /dev/raw1394
fi
./dev.py --set-workdir /data/ibeis/
./reset_dbs.py --reset-all
rm -rf failed_doctests.txt
./run_tests.py
