#!/bin/bash -ex
cd /opt/ibeis/ibeis
git pull
# Because Scipy is a little bitch and needs a lot of memory for compiling...
# Enable 1GB of swap
sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
sudo /sbin/mkswap /var/swap.1
sudo /sbin/swapon /var/swap.1
# Install major prerequisites
./_scripts/__install_prereqs__.sh
sudo apt-get -y install libopencv-dev python-opencv
# Fix problem with GraphViz
sudo pip uninstall pygraphviz
sudo pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"
# We are now done compiling the major dependencies...
# Disable swap
sudo swapoff /var/swap.1
sudo rm /var/swap.1
# Continue with additional dependencies
cd ../
git clone https://github.com/Theano/Theano.git
cd Theano
sudo python setup.py develop
cd ../
git clone https://github.com/lisa-lab/pylearn2.git
cd pylearn2
sudo python setup.py develop
cd ../
git clone https://github.com/Lasagne/Lasagne.git
cd Lasagne
sudo python setup.py develop
cd ../
cd ibeis

