#!/bin/bash
cd /opt/
sudo mkdir ibeis
sudo chown ubuntu ibeis
cd ibeis
sudo apt-get -y install git
sudo apt-get -y install tmux
sudo apt-get -y install htop
git clone https://github.com/Erotemic/ibeis.git
cd ibeis
git checkout next
git pull
./super_setup.py --bootstrap

